let alpineInstance;

export function setAlpine(Alpine) {
  alpineInstance = Alpine;
}

export function alpine() {
  return alpineInstance || window.Alpine;
}

const isElement = (node) => node?.nodeType === 1;
const keyOf = (node) => (isElement(node) ? node.getAttribute("key") : null);
const isDirective = (name) => name !== "x-cloak" && /^(x-|:|@)/.test(name);
const hasDirective = (el, name) => {
  for (const attr of el.attributes)
    if (attr.name === name || attr.name.startsWith(`${name}.`)) return true;
  return false;
};

function destroy(node) {
  if (isElement(node)) alpine()?.destroyTree(node);
}

function initialize(node) {
  if (isElement(node) && node.isConnected) alpine()?.initTree(node);
}

// Alpine owns the live siblings generated by x-if and x-for templates.
function generatedNodes(template) {
  const nodes = [];
  if (template._x_currentIfEl) nodes.push(template._x_currentIfEl);
  for (const key of template._x_prevKeys || []) {
    const node = template._x_lookup?.[key];
    if (node) {
      nodes.push(node);
      if (node._x_currentIfEl) nodes.push(node._x_currentIfEl);
    }
  }
  return nodes;
}

function directivesChanged(oldNode, newNode) {
  for (const attr of oldNode.attributes) {
    if (
      isDirective(attr.name) &&
      newNode.getAttribute(attr.name) !== attr.value
    )
      return true;
  }
  for (const attr of newNode.attributes) {
    if (
      isDirective(attr.name) &&
      oldNode.getAttribute(attr.name) !== attr.value
    )
      return true;
  }
  return false;
}

function syncAttributes(oldNode, newNode) {
  const managed = new Set();
  for (const attr of newNode.attributes) {
    const match = attr.name.match(/^(?:x-bind:|:)([^.]+)/);
    if (match) {
      const name = attr.name.split(".").includes("camel")
        ? match[1].replace(/-([a-z])/g, (_, char) => char.toUpperCase())
        : match[1];
      managed.add(name);
    }
  }
  if (newNode.hasAttribute("x-bind")) {
    // Object bindings can own arbitrary attributes. Preserve their live values.
    for (const attr of oldNode.attributes)
      if (!isDirective(attr.name)) managed.add(attr.name);
  }
  const hasShow = hasDirective(newNode, "x-show");
  const display = hasShow ? oldNode.style.display : null;
  const displayPriority = hasShow
    ? oldNode.style.getPropertyPriority("display")
    : "";
  for (const attr of Array.from(oldNode.attributes)) {
    if (
      !newNode.hasAttribute(attr.name) &&
      !managed.has(attr.name) &&
      !(hasShow && attr.name === "style")
    ) {
      oldNode.removeAttributeNode(attr);
    }
  }
  for (const attr of newNode.attributes) {
    if (attr.name === "x-cloak" && oldNode._x_marker) continue;
    if (
      !managed.has(attr.name) &&
      oldNode.getAttribute(attr.name) !== attr.value
    ) {
      // setAttribute('@click', ...) throws; parsed Attr nodes support Alpine shorthand.
      oldNode.setAttributeNodeNS(attr.cloneNode());
    }
  }
  if (hasShow && !managed.has("style")) {
    // Merge server styles while retaining Alpine's current visibility.
    oldNode.style.cssText = newNode.getAttribute("style") || "";
    if (display) oldNode.style.setProperty("display", display, displayPriority);
    else oldNode.style.removeProperty("display");
  }
}

const bound = (el, name) =>
  el.hasAttribute("x-bind") ||
  hasDirective(el, `x-bind:${name}`) ||
  hasDirective(el, `:${name}`);

function syncControl(oldNode, newNode) {
  if (!["INPUT", "TEXTAREA", "SELECT"].includes(oldNode.tagName)) return;
  if (hasDirective(oldNode, "x-model")) return;
  const valueBound = bound(oldNode, "value");
  if (oldNode.tagName === "INPUT") {
    if (
      !valueBound &&
      oldNode.type !== "file" &&
      oldNode.value !== newNode.value
    )
      oldNode.value = newNode.value;
    if (!bound(oldNode, "checked")) oldNode.checked = newNode.checked;
  } else if (oldNode.tagName === "TEXTAREA") {
    if (!valueBound && oldNode.value !== newNode.value)
      oldNode.value = newNode.value;
  } else if (oldNode.tagName === "SELECT") {
    // Inserting a selected option can change the live value without rerunning
    // Alpine's binding effect. Reapply its cached value after reconciling options.
    if (valueBound && oldNode._x_bindings && "value" in oldNode._x_bindings) {
      const values = new Set([].concat(oldNode._x_bindings.value).map(String));
      for (const option of oldNode.options)
        option.selected = values.has(option.value);
      if (
        !oldNode.multiple &&
        !Array.from(oldNode.options).some((option) => values.has(option.value))
      )
        oldNode.selectedIndex = -1;
    } else if (!valueBound) {
      let hasBoundOption = false;
      for (let i = 0; i < oldNode.options.length; i++) {
        if (bound(oldNode.options[i], "selected")) {
          hasBoundOption = true;
          continue;
        }
        oldNode.options[i].selected = newNode.options[i]?.selected || false;
      }
      if (!oldNode.multiple && !hasBoundOption)
        oldNode.selectedIndex = newNode.selectedIndex;
    }
  }
}

function patch(parent, oldNode, newNode) {
  if (!newNode) {
    if (oldNode) {
      destroy(oldNode);
      oldNode.remove();
    }
    return null;
  }
  if (oldNode === newNode) return oldNode;
  if (
    oldNode &&
    isElement(oldNode) &&
    (oldNode.hasAttribute("x-ignore") || newNode.hasAttribute?.("x-ignore"))
  ) {
    return oldNode;
  }
  if (
    !oldNode ||
    oldNode.nodeType !== newNode.nodeType ||
    oldNode.nodeName !== newNode.nodeName ||
    oldNode.namespaceURI !== newNode.namespaceURI ||
    keyOf(oldNode) !== keyOf(newNode) ||
    (isElement(oldNode) && directivesChanged(oldNode, newNode))
  ) {
    // Clone: incoming DOM stays intact so control defaults and scripts remain available.
    const replacement = newNode.cloneNode(true);
    if (oldNode) {
      destroy(oldNode);
      parent.replaceChild(replacement, oldNode);
    } else parent.appendChild(replacement);
    initialize(replacement);
    return replacement;
  }
  if (!isElement(oldNode)) {
    if (oldNode.nodeValue !== newNode.nodeValue)
      oldNode.nodeValue = newNode.nodeValue;
    return oldNode;
  }
  syncAttributes(oldNode, newNode);
  if (!oldNode.hasAttribute("x-text") && !oldNode.hasAttribute("x-html")) {
    if (oldNode.tagName === "TEMPLATE") {
      // Existing structural templates are client-owned. A changed template must
      // be reinitialized so x-if/x-for clones reflect the new server markup.
      if (!oldNode.content.isEqualNode(newNode.content)) {
        const replacement = newNode.cloneNode(true);
        destroy(oldNode);
        parent.replaceChild(replacement, oldNode);
        initialize(replacement);
        return replacement;
      }
    } else {
      patchChildren(oldNode, newNode);
    }
  }
  syncControl(oldNode, newNode);
  // Option/attribute changes can alter a modeled control without firing its effect.
  oldNode._x_forceModelUpdate?.(oldNode._x_model.get());
  return oldNode;
}

function patchChildren(oldNode, newNode) {
  const allOld = Array.from(oldNode.childNodes);
  const generated = new Set(allOld.flatMap(generatedNodes));
  const oldChildren = allOld.filter(
    (node) => !generated.has(node) && !node._x_teleportBack,
  );
  const keyed = new Map();
  const unkeyed = [];
  for (const child of oldChildren) {
    const key = keyOf(child);
    if (key === null) unkeyed.push(child);
    else {
      // Duplicate keys are matched in occurrence order, without reusing a node.
      if (!keyed.has(key)) keyed.set(key, { nodes: [], index: 0 });
      keyed.get(key).nodes.push(child);
    }
  }
  const used = new Set();
  let unkeyedIndex = 0;
  let cursor = oldNode.firstChild;
  for (const incoming of newNode.childNodes) {
    const key = keyOf(incoming);
    const bucket = key === null ? null : keyed.get(key);
    const matching =
      key === null ? unkeyed[unkeyedIndex++] : bucket?.nodes[bucket.index++];
    if (matching) used.add(matching);
    const atCursor = matching === cursor;
    const live = patch(oldNode, matching, incoming);
    if (atCursor) cursor = live;
    if (live !== cursor) oldNode.insertBefore(live, cursor);
    cursor = live.nextSibling;
    for (const child of generatedNodes(live)) {
      if (child !== cursor) oldNode.insertBefore(child, cursor);
      cursor = child.nextSibling;
    }
  }
  for (const child of oldChildren) {
    if (!used.has(child) && child.parentNode === oldNode) {
      destroy(child);
      child.remove();
    }
  }
}

/** Reconcile in O(n + attributes) per sibling list, retaining keyed node identity. */
export function diffAndPatch(parent, oldNode, newNode) {
  const active = document.activeElement;
  const selection =
    active && typeof active.selectionStart === "number"
      ? [active.selectionStart, active.selectionEnd, active.selectionDirection]
      : null;
  // Alpine.mutateDom doesn't restart its observer when its callback throws.
  let failure;
  const run = () => {
    try {
      return patch(parent, oldNode, newNode);
    } catch (error) {
      failure = error;
    }
  };
  const result = alpine()?.mutateDom ? alpine().mutateDom(run) : run();
  if (active?.isConnected && document.activeElement !== active) {
    active.focus({ preventScroll: true });
    if (selection && typeof active.selectionStart === "number")
      active.setSelectionRange(...selection);
  }
  if (failure) throw failure;
  return result;
}

/** Requires exactly one element root; invalid responses leave the live DOM intact. */
export async function replaceHtml(targetEl, html, baseUrl = document.baseURI) {
  if (typeof html !== "string")
    throw new TypeError("FireLine HTML must be a string.");
  const template = document.createElement("template");
  template.innerHTML = html.trim();
  const roots = Array.from(template.content.childNodes).filter(
    (node) =>
      node.nodeType !== 8 && !(node.nodeType === 3 && !node.textContent.trim()),
  );
  if (
    roots.length !== 1 ||
    !isElement(roots[0]) ||
    roots[0].tagName === "SCRIPT"
  ) {
    throw new Error(
      "FireLine HTML must contain exactly one root element (not a full document).",
    );
  }
  if (
    /^(?:\s|<!--[\s\S]*?-->)*(?:<!doctype|<html[\s>]|<head[\s>]|<body[\s>])/i.test(
      html,
    )
  )
    throw new Error("FireLine requires a page fragment.");
  if (!targetEl?.parentNode)
    throw new Error("Router target element is detached.");
  const newContent = roots[0];
  const doReplace = () => diffAndPatch(targetEl.parentNode, targetEl, newContent);
  let live;
  if (window.FireLine?.settings.viewTransitions && document.startViewTransition) {
      await new Promise(resolve => {
          const transition = document.startViewTransition(() => {
              live = doReplace();
              resolve();
          });
          // Ensure resolve is called if transition fails
          transition.finished.catch(() => resolve());
      });
  } else {
      live = doReplace();
  }
  
  if (window.FireLine?.settings.executeScripts !== false) {
    await injectScripts(newContent.querySelectorAll("script"), baseUrl);
  }
  return live;
}

/** Execute trusted fragment scripts after patching; await external scripts in order. */
export async function injectScripts(scripts, baseUrl = document.baseURI) {
  for (const source of scripts) {
    const type = (source.type || "").trim().toLowerCase();
    if (
      type &&
      !["module", "text/javascript", "application/javascript"].includes(type)
    )
      continue;
    const script = document.createElement("script");
    for (const attr of source.attributes)
      script.setAttributeNodeNS(attr.cloneNode());
    if (source.hasAttribute("src"))
      script.src = new URL(source.getAttribute("src"), baseUrl).href;
    if (source.noModule && "noModule" in script) continue;
    script.textContent = source.textContent;
    script.async = false;
    if (source.hasAttribute("src")) {
      await new Promise((resolve, reject) => {
        let timer;
        const finish = (error) => {
          clearTimeout(timer);
          script.remove();
          error ? reject(error) : resolve();
        };
        script.onload = () => finish();
        script.onerror = () =>
          finish(
            new Error(
              `FireLine script failed: ${script.src || "inline module"}`,
            ),
          );
        const timeout = window.FireLine?.settings.timeout ?? 30;
        if (timeout > 0)
          timer = setTimeout(
            () =>
              finish(
                new Error(
                  `FireLine script timed out: ${script.src || "inline module"}`,
                ),
              ),
            timeout * 1000,
          );
        document.head.appendChild(script);
      });
    } else {
      document.head.appendChild(script);
      script.remove();
    }
  }
}
